/**
 * Builds setup.sql: every schema file in supabase/, in dependency order, as
 * one script for a brand-new Supabase project. Paste setup.sql into the SQL
 * editor and run it once. Every file is safe to re-run.
 *
 *   node packages/database/build-setup.mjs
 *
 * Add a new schema file to ORDER after the files whose tables it uses.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, "supabase");

const ORDER = [
  "profiles",
  "profiles-personal-contact",
  "beneficiaries",
  "beneficiaries-delete",
  "swift-save",
  "notification-dismissals",
  "payment-received-notifications",
  "payment-request-declined",
  "recurring-schedules",
  "recurring-autopay-mandates",
  "payment-policies",
  "payment-policies-timezone",
  "payment-intents",
  "payment-intents-cancelled",
  // Workspaces are no longer a feature and nothing creates one, but the
  // tables stay until the code stops reading them: /api/onboarding (loaded
  // on every page by WorkspaceProvider) fails without `workspaces`, and
  // account-business's cleanup block references it.
  "business-workspaces",
  "account-business",
  "business-profile-details",
  "business-verification-reviews",
  "business-payroll",
  "earn-vault",
  "referral-and-swiftpoints",
  "referral-progress-payments",
  "swiftpoints-economy-and-auto-deposit",
  "swiftpoints-entitlement-term",
  "swiftpoints-payroll-feature",
  "swiftpoints-and-auto-deposit-rls",
  "swift-circle",
  "agent-wallets",
  "allie-monetization",
  "account-activity",
  "support-chat",
  "rate-limits",
  "incoming-transfer-cursors",
  "app-lock",
  "traction-events",
];

/** Not part of a new database: one-off fixes to existing data, or unused. */
const SKIPPED = new Set([
  "confidential-payments", // no app code uses these tables
  "profiles-reset-circle-links", // one-time data reset
  "recurepay-executor-migration", // one-time data migration
  "recurring-autopay-autonomous", // comment only; points at recurring-schedules
]);

const present = readdirSync(dir)
  .filter((name) => name.endsWith(".sql"))
  .map((name) => name.slice(0, -4));
const unlisted = present.filter((name) => !ORDER.includes(name) && !SKIPPED.has(name));
if (unlisted.length > 0) {
  throw new Error(`Add these to ORDER or SKIPPED: ${unlisted.join(", ")}`);
}

const parts = ORDER.map((name) => {
  const sql = readFileSync(join(dir, `${name}.sql`), "utf8").trimEnd();
  return `-- ═══ ${name}.sql ${"═".repeat(Math.max(4, 66 - name.length))}\n\n${sql}\n`;
});

const header = `-- SwiftPay database setup for a NEW Supabase project.
-- Generated by packages/database/build-setup.mjs — edit the files in
-- supabase/ and rebuild; do not edit this file by hand.
--
-- Supabase → SQL Editor → New query → paste this whole file → Run.
-- Safe to run again: every statement is idempotent.
`;

writeFileSync(join(here, "setup.sql"), `${header}\n${parts.join("\n")}`);
console.log(`Wrote setup.sql from ${ORDER.length} files.`);
